### ISSUE TITLE
Rename "Open Custom..."

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigdataprocessor2#120]
@nornil @seadaisy
What about renaming "Open Custom..." to something like "Open Image Sequence...", because the point is that the data is distributed across several files.

**Comment by nornil** [comment]
Sounds better. I agree.

**Comment by seadaisy** [comment]
I agree.

S

 

From: noreply@github.com <noreply@github.com> 
Sent: Sonntag, 4. Oktober 2020 20:04
To: bigdataprocessor/bigdataprocessor2 <bigdataprocessor2@noreply.github.com>
Cc: seadaisy <sreither@embl.de>; Mention <mention@noreply.github.com>
Subject: [bigdataprocessor/bigdataprocessor2] Rename "Open Custom..." (#120)

 

@nornil <https://github.com/nornil>  @seadaisy <https://github.com/seadaisy> 
What about renaming "Open Custom..." to something like "Open Image Sequence...", because the point is that the data is distributed across several files.

**Comment by tischi** [comment]
@nornil What about `Open File Series...` maybe even more to the point?!
