### ISSUE TITLE
Opening HDF5 with BDP2

### ISSUE THREAD

**Issue by cikus3** [bigdataprocessor/bigdataprocessor2#199]
Dear Tischi, hope you are doing fine;  I`m back using the belowed pluigin and I`m testing it also for different machine/micrscopes..My current issue is opening HDF5 (H 5)files (and then ideally process them); what I have noticesd is that
- if I open and H5 file (using teh BioFormat option) with BDP2 it works, but exploring the data is much much much slower than opening the same file with BDV; any reason for tha? Anty trick to make the exploration/loading faster? Note that the H5 file was made using BDV exporter
- if I try to open a file with BDP2 Open single H5, I can`t; alwasys get errors (see attach); can`t finbd the proper naming (if that is the problem) to open it; what is the proper naming and format for an H5 to be opened with BDP2?
Thanks in advance,
cheers,
Alessandro
![image](https://user-images.githubusercontent.com/35956783/213690226-1f1cfa3a-b1c7-4f12-926f-32bf616a6381.png)

**Comment by tischi** [comment]
Hi,

Happy new year :-)

1. the BDV XML/HDF5 file format is a multi-resolution format, thus it opens very fast, this is in fact the whole point :-)
2. BDP2 is a single-resolution tool, thus it will only open the highest resolution from the BDV XML/HDF5, thus it is slow in opening data.
3. You cannot open a BDV H5 directly in BDP2 without the XML because it does know where to find the data within the HDF5 (as mentioned the BDV HDF5 files are internally a bit more complex due to the multi-resolution).

What we are missing in Fiji is a tool for processing such multi-resolution data, but this is not trivial and I would not know of any attempts.

**Comment by cikus3** [comment]
Hi Tischi, just realized that I forgot to thank you for the reply..All clear, thanks again; cheers, Alessandro
