### ISSUE TITLE
Menu structure

### ISSUE THREAD

**Issue by tischi** [bigdataprocessor/bigDataProcessor2#84]
@seadaisy
Which menu structure do you find intuitive?
In my development version it currently looks like this:
![image](https://user-images.githubusercontent.com/2157566/79338079-ec68d700-7f26-11ea-9174-e61ab1e1256a.png)
![image](https://user-images.githubusercontent.com/2157566/79338092-f25eb800-7f26-11ea-93b7-e3c134a70aa4.png)
![image](https://user-images.githubusercontent.com/2157566/79338103-f8ed2f80-7f26-11ea-94f1-83c509452d34.png)
![image](https://user-images.githubusercontent.com/2157566/79338120-fe4a7a00-7f26-11ea-9eb1-f66ea58ee138.png)

**Comment by seadaisy** [comment]
@tischi 
If you whant , as you mentioned in our discussion, to have only steps where values are changed in the **Process** menu, I would move the **Aling** steps to the **Image** menu.

**Comment by tischi** [comment]
But then also `Crop...` should go to image, no? 
Only `Bin...` and `8-bit` change the values.
I am not sure, because even those two are also under `Image` in ImageJ. 
So maybe everything in the main menu, and `Save` the only submenu?

**Comment by seadaisy** [comment]
Let's discuss at 17:00

**Comment by seadaisy** [comment]
@tischi 
I will write the conclusion of the discussion with Nils via Mail (to keep him in the loop).

**Comment by seadaisy** [comment]
@tischi 
**DP Menu structure**
From **FIJI**
Why do I get all menus if I go via FIJI [Plugins->BigDataProcessor2 -> BDPCalibrate
								  ->Open
								  ->Process
								  -> Save
Even if there is no open image and therefore nothing to process or to save (it even gives an error massage if you choose something from the Process or Save menu

Insight **BDP2**
 [BigDataProcessor-> Calibrate] Calibrate should be renamed to Properties (because it is doing the same, as the FIJI I[mage -> Properties] dialog
Is t possible to have [BigDataProcessor->Open]?

Include [BigDataProcessor->Process->Align Channels  
  	      ->Align Channels Split Chip..

Leave the rest as it is (Nils had a strong opinion to leave it, because it is easy to understand from a biologist point of view)
Additional recommendation: If you can foresee, that there will be more options in terms of processing coming in the **near future**, splitting the Process menu is recommended
